### ISSUE TITLE
Named Character References

### ISSUE THREAD

**Issue by jordanwillis** [eabooth89/prj-rev-bwfs-dasmoto#1]
Great job using a named character reference to represent the ampersand in the main heading!  Just a quick reminder that named character references always end with a semi-colon so in this case it would be.

`&amp;` instead of `&amp`

https://github.com/eabooth89/prj-rev-bwfs-dasmoto/blob/master/Dasmotos_project/index.html#L9

Fortunately, browsers these day are pretty lenient and understand what your intentions are, but old browsers or screen readers might have trouble when the ; is missing.

**Comment by eabooth89** [comment]
I will definitely remember that in the future. Thanks!
