### ISSUE TITLE
Context-less <div>'s

### ISSUE THREAD

**Issue by jordanwillis** [eabooth89/prj-rev-bwfs-dasmoto#2]
First off, great job recognizing that each of the page item sections should be wrapped in some sort of container.  This is a great practice because it can make sure HTML more semantic and 9 times out of 10 you will want a way to reference the component as a whole for styling or interaction (e.g. JavaScript) reasons.

With that said, I would recommend never using a `<div>` without providing some sort of context through a class name or ID.  Going back to semantic HTML, the `<div>` element literally has no meaning (vs. other container elements such as `<nav>`, `<article>`, `<section>`, etc.).  In this case I would recommend going with a simple class name that describes the set of components.

``` html
<div class="item>
  <!-- rest of code here -->
</div>
```

Also, by providing a class, you can ensure that any styling can be done within the context of the component instead of having to create a broad rule against an entire selector.

``` css
.item h2 {
  font-size: 32px;
  color: white;
}
```

vs.

https://github.com/eabooth89/prj-rev-bwfs-dasmoto/blob/87f42033a403629415d4df8a63d758d7cc80ce42/Dasmotos_project/resources/style.css#L9-L14

**Comment by eabooth89** [comment]
The <section> vs <div> is something that I learned in one of the free classes and for some reason always get it backwards of which is better. Making a note of this for future reference.
