### ISSUE TITLE
<cost> Element

### ISSUE THREAD

**Issue by jordanwillis** [eabooth89/prj-rev-bwfs-dasmoto#3]
I noticed that you wrapped the prices in an element called `<cost>`.  There is actually no just element that exists, so instead you should just use a simple `<span>` (since the price's are inline) with a class name such as `cost` or 'price' that gives some good context.

https://github.com/eabooth89/prj-rev-bwfs-dasmoto/blob/master/Dasmotos_project/index.html#L15
https://github.com/eabooth89/prj-rev-bwfs-dasmoto/blob/master/Dasmotos_project/index.html#L22
https://github.com/eabooth89/prj-rev-bwfs-dasmoto/blob/master/Dasmotos_project/index.html#L29

``` html
<p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="price">Starting at $3.00/ brush.</span></p>
```

To be honest, I was surprised that the browser even applied the CSS rules that you create for `cost`, but as I said earlier, browsers are quite lenient these days and are good about understanding your intentions.

**Comment by eabooth89** [comment]
Yeah, I actually was surprised too but didn't question it too much when it worked. Good to remember the <span> tag for inline stuff. Thanks!
