### ISSUE TITLE
Summary: Grade = Exceed Expectations

### ISSUE THREAD

**Issue by jordanwillis** [eabooth89/prj-rev-bwfs-dasmoto#4]
Overall you did an outstanding job on this project!  Your HTML was nicely structured and your CSS was great too.

In the future, I would recommend reviewing your css at the end of a project to make sure it is DRY (don't repeat yourself) by removing duplicates properties/styles.  You did a great job with this on this project, but there was at least one property that was duplicated several times (`font-family: Helvetica;`).  One technique to eliminate this is to create a combo selector rules such as this.

``` css
h1, 
h2, 
h3, 
p {
  font-family: "Helvetica", sans-serif;
}
```

Then in the future if you decide to change the font you only have to change it in one place (one of the main benefits of DRY).

Keep up the great work!

**Comment by eabooth89** [comment]
Thanks!
